name: CI/CD Pipeline with Github Actions

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the files
        uses: actions/checkout@v2

      - name: Setup SSH connection
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy code
        run: |
          ssh-keyscan 3.1.8.35 >> ~/.ssh/known_hosts
          rsync -avz --delete --no-perms --exclude-from='.rsyncignore' ./ ubuntu@3.1.8.35:/var/www/html/app/