name: CI/CD Pipeline with Github Actions

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the files
        uses: actions/checkout@v2

      - name: Setup SSH connection to jump server
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Add jump server to known_hosts
        run: ssh-keyscan 43.205.199.65 >> ~/.ssh/known_hosts

      - name: Setup SSH connection to destination server through jump server
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}
          ssh-auth-sock: $SSH_AUTH_SOCK
          ssh-options: '-o ProxyCommand="ssh -W %h:%p -i ${{ secrets.EC2_SSH_KEY }} ubuntu@43.205.199.65" ubuntu@172.20.3.120'

      - name: Deploy code to destination server
        run: rsync -avz --delete --no-perms --exclude-from='.rsyncignore' ./ ubuntu@localhost:/var/www/html/