name: CI/CD Pipeline with Github Actions

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the files
        uses: actions/checkout@v2

      - name: Setup SSH connection to jump server
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Create SSH tunnel to target server through jump server
        run: ssh -fNL 2222:172.20.3.120:22 ubuntu@43.205.199.65 -i ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy code to target server through tunnel
        run: |
          rsync -avz --delete --no-perms --exclude-from='.rsyncignore' ./ ubuntu@localhost:/var/www/html/
