name: CI/CD Pipeline with Github Actions

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy code via rsync
        run: |
          ssh-keyscan 172.20.3.120 >> ~/.ssh/known_hosts
          rsync -avz -e "ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i ${{ secrets.EC2_SSH_KEY }}" ./ ubuntu@172.20.3.120:/var/www/html/