name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:


  deploy:
    name: Deploy to EC2 on master branch push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the files
        uses: actions/checkout@v2

      - name: Deploy to Server 1
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: /var/www/html/  # update this line
        with:
          args: rsync -azv -e "ssh -p 22 -i app_key_pair.pem -o StrictHostKeyChecking=no" --exclude-from='.rsyncignore' --delete $GITHUB_WORKSPACE/ ubuntu@$18.136.196.164:/var/www/html/
