name: Test

on:
  push:
    branches:
      - master

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'

      - name: Install dependencies
        run: composer install

      - name: Grant Permission
        run: chmod +x vendor/bin/phpunit

      - name: Run tests
        run: vendor/bin/phpunit tests/
