name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:

  build:
    name: Build project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y apache2 libapache2-mod-php composer
          composer install

  test:
    name: Unit tests
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'

      - name: Install dependencies
        run: composer install

      - name: Grant Permission
        run: chmod +x vendor/bin/phpunit

      - name: Run tests
        run: vendor/bin/phpunit tests/

  deploy:
    name: Deploy code
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Load SSH key
        uses: appleboy/ssh-action@master
        with:
            host: ${{ secrets.HOST }}
            username: ${{ secrets.USERNAME }}
            ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
            port: ${{ secrets.PORT }}

      - name: Install Apache and PHP
        run: |
          sudo apt-get update
          sudo apt-get install -y apache2
          sudo apt-get install -y php7.4 libapache2-mod-php7.4

      - name: Start Apache
        run: sudo systemctl start apache2

      - name: Enable Apache on boot
        run: sudo systemctl enable apache2

      - name: Check Apache status
        run: sudo systemctl status apache2

      - name: Check PHP version
        run: php -v

      - name: Deploy code
        run: |
          rsync -avz --delete --exclude-from='.rsyncignore' ./ ubuntu@18.136.196.164:/var/www/html/
          ssh ubuntu@18.136.196.164 'cd /var/www/html && composer install'
