name: CI/CD Pipeline with Github Actions

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the files
        uses: actions/checkout@v2

      - name: Setup SSH connection to jump server
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Connect to private EC2 instance and deploy code
        run: |
          ssh-keyscan 172.20.3.120 >> ~/.ssh/known_hosts
          ssh -o ProxyJump=ubuntu@43.205.199.65 -i ${{ secrets.EC2_SSH_KEY }} ubuntu@172.20.3.120 "rsync -avz --delete --no-perms --exclude-from='.rsyncignore' ./ /var/www/html/"
    
