name: CI/CD Pipeline with Github Actions

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the files
        uses: actions/checkout@v2

      - name: Setup SSH connection to jump server
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Setup SSH connection to destination server through jump server
        uses: webfactory/ssh-agent@v0.5.0
        with:
          host: 172.20.3.120
          username: ubuntu
          port: 80
          ssh-private-key: ${{ secrets.APP_SSH_KEY }}
          jump_host: ubuntu@43.205.199.65
          jump_key: ${{ secrets.APP_SSH_KEY }}

      - name: Deploy code to destination server
        run: |
          rsync -avz --delete --no-perms --exclude-from='.rsyncignore' ./ ubuntu@localhost:/var/www/html/