name: CI/CD Pipeline with Github Actions

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the files
        uses: actions/checkout@v2

      - name: Setup SSH connection to jump server
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Forward SSH port to EC2 instance
        run: |
          ssh -f -N -L 2222:172.20.3.120:22 ubuntu@43.205.199.65

      - name: Deploy code to EC2 instance
        run: |
          ssh-keyscan 43.205.199.65 >> ~/.ssh/known_hosts
          rsync -avz --delete --no-perms --exclude-from='.rsyncignore' -e 'ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -p 2222' ./ ubuntu@localhost:/var/www/html/
